version: '3.8'

services:
  app:
    image: jessicacarmelita11/loanly-api:latest
    container_name: loanly-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://db:1433;databaseName=loanDatabase;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=YourStrong@Passw0rd
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      # Mailtrap configuration (Using defaults from application.properties or override here)
      # - SPRING_MAIL_USERNAME=...
      # - SPRING_MAIL_PASSWORD=...
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json
    depends_on:
      - db
      - redis
    networks:
      - loanly-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: loanly-db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - loanly-network

  redis:
    image: redis:alpine
    container_name: loanly-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - loanly-network

networks:
  loanly-network:
    driver: bridge

volumes:
  db_data:
